# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RandomSystemDialog.ui'
#
# Created: Sun Feb 12 13:39:16 2012
#      by: PyQt4 UI code generator 4.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_RandomSystemDialog(object):
    def setupUi(self, RandomSystemDialog):
        RandomSystemDialog.setObjectName(_fromUtf8("RandomSystemDialog"))
        RandomSystemDialog.resize(279, 251)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RandomSystemDialog.sizePolicy().hasHeightForWidth())
        RandomSystemDialog.setSizePolicy(sizePolicy)
        RandomSystemDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(RandomSystemDialog)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.centralwidget = QtGui.QWidget(RandomSystemDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_3.addWidget(self.label_6)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_3.addWidget(self.label_7)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.n = QtGui.QLineEdit(self.centralwidget)
        self.n.setObjectName(_fromUtf8("n"))
        self.verticalLayout_2.addWidget(self.n)
        self.t1 = QtGui.QLineEdit(self.centralwidget)
        self.t1.setObjectName(_fromUtf8("t1"))
        self.verticalLayout_2.addWidget(self.t1)
        self.t2 = QtGui.QLineEdit(self.centralwidget)
        self.t2.setObjectName(_fromUtf8("t2"))
        self.verticalLayout_2.addWidget(self.t2)
        self.v1 = QtGui.QLineEdit(self.centralwidget)
        self.v1.setObjectName(_fromUtf8("v1"))
        self.verticalLayout_2.addWidget(self.v1)
        self.v2 = QtGui.QLineEdit(self.centralwidget)
        self.v2.setObjectName(_fromUtf8("v2"))
        self.verticalLayout_2.addWidget(self.v2)
        self.tdir = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tdir.sizePolicy().hasHeightForWidth())
        self.tdir.setSizePolicy(sizePolicy)
        self.tdir.setObjectName(_fromUtf8("tdir"))
        self.tdir.addItem(_fromUtf8(""))
        self.tdir.addItem(_fromUtf8(""))
        self.tdir.addItem(_fromUtf8(""))
        self.tdir.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tdir)
        self.rdir = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rdir.sizePolicy().hasHeightForWidth())
        self.rdir.setSizePolicy(sizePolicy)
        self.rdir.setObjectName(_fromUtf8("rdir"))
        self.rdir.addItem(_fromUtf8(""))
        self.rdir.addItem(_fromUtf8(""))
        self.rdir.addItem(_fromUtf8(""))
        self.rdir.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.rdir)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.OK = QtGui.QPushButton(self.centralwidget)
        self.OK.setObjectName(_fromUtf8("OK"))
        self.horizontalLayout.addWidget(self.OK)
        self.Cancel = QtGui.QPushButton(self.centralwidget)
        self.Cancel.setObjectName(_fromUtf8("Cancel"))
        self.horizontalLayout.addWidget(self.Cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout_3.addWidget(self.centralwidget)

        self.retranslateUi(RandomSystemDialog)
        self.tdir.setCurrentIndex(2)
        self.rdir.setCurrentIndex(2)
        QtCore.QObject.connect(self.OK, QtCore.SIGNAL(_fromUtf8("clicked()")), RandomSystemDialog.accept)
        QtCore.QObject.connect(self.Cancel, QtCore.SIGNAL(_fromUtf8("clicked()")), RandomSystemDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(RandomSystemDialog)

    def retranslateUi(self, RandomSystemDialog):
        RandomSystemDialog.setWindowTitle(QtGui.QApplication.translate("RandomSystemDialog", "Create Random System", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("RandomSystemDialog", "Number of vertices", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("RandomSystemDialog", "Mimimal time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("RandomSystemDialog", "Maximal time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("RandomSystemDialog", "Minimal volume", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("RandomSystemDialog", "Maximal volume", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("RandomSystemDialog", "Time constraint", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("RandomSystemDialog", "Reliability constraint", None, QtGui.QApplication.UnicodeUTF8))
        self.n.setText(QtGui.QApplication.translate("RandomSystemDialog", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.t1.setText(QtGui.QApplication.translate("RandomSystemDialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.t2.setText(QtGui.QApplication.translate("RandomSystemDialog", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.v1.setText(QtGui.QApplication.translate("RandomSystemDialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.v2.setText(QtGui.QApplication.translate("RandomSystemDialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.tdir.setItemText(0, QtGui.QApplication.translate("RandomSystemDialog", "Impossible", None, QtGui.QApplication.UnicodeUTF8))
        self.tdir.setItemText(1, QtGui.QApplication.translate("RandomSystemDialog", "Strict", None, QtGui.QApplication.UnicodeUTF8))
        self.tdir.setItemText(2, QtGui.QApplication.translate("RandomSystemDialog", "Normal", None, QtGui.QApplication.UnicodeUTF8))
        self.tdir.setItemText(3, QtGui.QApplication.translate("RandomSystemDialog", "Nonexisting", None, QtGui.QApplication.UnicodeUTF8))
        self.rdir.setItemText(0, QtGui.QApplication.translate("RandomSystemDialog", "Impossible", None, QtGui.QApplication.UnicodeUTF8))
        self.rdir.setItemText(1, QtGui.QApplication.translate("RandomSystemDialog", "Strict", None, QtGui.QApplication.UnicodeUTF8))
        self.rdir.setItemText(2, QtGui.QApplication.translate("RandomSystemDialog", "Normal", None, QtGui.QApplication.UnicodeUTF8))
        self.rdir.setItemText(3, QtGui.QApplication.translate("RandomSystemDialog", "Nonexisting", None, QtGui.QApplication.UnicodeUTF8))
        self.OK.setText(QtGui.QApplication.translate("RandomSystemDialog", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.Cancel.setText(QtGui.QApplication.translate("RandomSystemDialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

