# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Viewer.ui'
#
# Created: Thu Dec 22 15:51:10 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Viewer(object):
    def setupUi(self, Viewer):
        Viewer.setObjectName(_fromUtf8("Viewer"))
        Viewer.resize(497, 385)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/chart.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Viewer.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(Viewer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 491, 341))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.visualizerArea = QtGui.QScrollArea(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visualizerArea.sizePolicy().hasHeightForWidth())
        self.visualizerArea.setSizePolicy(sizePolicy)
        self.visualizerArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.visualizerArea.setWidgetResizable(False)
        self.visualizerArea.setObjectName(_fromUtf8("visualizerArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 635, 215))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.visualizerArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.visualizerArea)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.rewind = QtGui.QPushButton(self.layoutWidget)
        self.rewind.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rewind.sizePolicy().hasHeightForWidth())
        self.rewind.setSizePolicy(sizePolicy)
        self.rewind.setMaximumSize(QtCore.QSize(31, 16777215))
        self.rewind.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/rewind.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rewind.setIcon(icon1)
        self.rewind.setIconSize(QtCore.QSize(32, 32))
        self.rewind.setFlat(True)
        self.rewind.setObjectName(_fromUtf8("rewind"))
        self.horizontalLayout_2.addWidget(self.rewind)
        self.stepback = QtGui.QPushButton(self.layoutWidget)
        self.stepback.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepback.sizePolicy().hasHeightForWidth())
        self.stepback.setSizePolicy(sizePolicy)
        self.stepback.setMaximumSize(QtCore.QSize(31, 16777215))
        self.stepback.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/skip_backward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stepback.setIcon(icon2)
        self.stepback.setIconSize(QtCore.QSize(32, 32))
        self.stepback.setFlat(True)
        self.stepback.setObjectName(_fromUtf8("stepback"))
        self.horizontalLayout_2.addWidget(self.stepback)
        self.lineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lineEdit.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.labelTotal = QtGui.QLabel(self.layoutWidget)
        self.labelTotal.setObjectName(_fromUtf8("labelTotal"))
        self.horizontalLayout_2.addWidget(self.labelTotal)
        self.stepforth = QtGui.QPushButton(self.layoutWidget)
        self.stepforth.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepforth.sizePolicy().hasHeightForWidth())
        self.stepforth.setSizePolicy(sizePolicy)
        self.stepforth.setMaximumSize(QtCore.QSize(31, 16777215))
        self.stepforth.setStyleSheet(_fromUtf8(""))
        self.stepforth.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/skip_forward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stepforth.setIcon(icon3)
        self.stepforth.setIconSize(QtCore.QSize(32, 32))
        self.stepforth.setFlat(True)
        self.stepforth.setObjectName(_fromUtf8("stepforth"))
        self.horizontalLayout_2.addWidget(self.stepforth)
        self.replay = QtGui.QPushButton(self.layoutWidget)
        self.replay.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replay.sizePolicy().hasHeightForWidth())
        self.replay.setSizePolicy(sizePolicy)
        self.replay.setMaximumSize(QtCore.QSize(31, 16777215))
        self.replay.setStyleSheet(_fromUtf8(""))
        self.replay.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/fast_forward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.replay.setIcon(icon4)
        self.replay.setIconSize(QtCore.QSize(32, 32))
        self.replay.setFlat(True)
        self.replay.setObjectName(_fromUtf8("replay"))
        self.horizontalLayout_2.addWidget(self.replay)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.labeltime = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labeltime.sizePolicy().hasHeightForWidth())
        self.labeltime.setSizePolicy(sizePolicy)
        self.labeltime.setObjectName(_fromUtf8("labeltime"))
        self.verticalLayout_3.addWidget(self.labeltime)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_3.addWidget(self.label_2)
        self.labelrel = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelrel.sizePolicy().hasHeightForWidth())
        self.labelrel.setSizePolicy(sizePolicy)
        self.labelrel.setObjectName(_fromUtf8("labelrel"))
        self.verticalLayout_3.addWidget(self.labelrel)
        self.label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.labelproc = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelproc.sizePolicy().hasHeightForWidth())
        self.labelproc.setSizePolicy(sizePolicy)
        self.labelproc.setObjectName(_fromUtf8("labelproc"))
        self.verticalLayout_3.addWidget(self.labelproc)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_3.addWidget(self.label_4)
        self.tdir = QtGui.QLabel(self.layoutWidget)
        self.tdir.setObjectName(_fromUtf8("tdir"))
        self.verticalLayout_3.addWidget(self.tdir)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_3.addWidget(self.label_6)
        self.rdir = QtGui.QLabel(self.layoutWidget)
        self.rdir.setObjectName(_fromUtf8("rdir"))
        self.verticalLayout_3.addWidget(self.rdir)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.verticalSlider = QtGui.QSlider(self.layoutWidget)
        self.verticalSlider.setSliderPosition(50)
        self.verticalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.verticalSlider.setObjectName(_fromUtf8("verticalSlider"))
        self.verticalLayout_3.addWidget(self.verticalSlider)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        Viewer.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Viewer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 497, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        Viewer.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Viewer)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Viewer.setStatusBar(self.statusbar)

        self.retranslateUi(Viewer)
        QtCore.QMetaObject.connectSlotsByName(Viewer)

    def retranslateUi(self, Viewer):
        Viewer.setWindowTitle(QtGui.QApplication.translate("Viewer", "Viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Viewer", "/", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTotal.setText(QtGui.QApplication.translate("Viewer", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Viewer", "Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.labeltime.setText(QtGui.QApplication.translate("Viewer", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Viewer", "Reliability:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelrel.setText(QtGui.QApplication.translate("Viewer", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Viewer", "Processors:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelproc.setText(QtGui.QApplication.translate("Viewer", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Viewer", "Time Limit:", None, QtGui.QApplication.UnicodeUTF8))
        self.tdir.setText(QtGui.QApplication.translate("Viewer", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Viewer", "Reliability Limit:", None, QtGui.QApplication.UnicodeUTF8))
        self.rdir.setText(QtGui.QApplication.translate("Viewer", "0", None, QtGui.QApplication.UnicodeUTF8))

from . import resources_rc
